<?php
$title = "Remover pessoa";
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<p>
    Você deseja realmente excluir "<?=$this->escapeHtml($usuario->getNome())?>"?
</p>

<form method="post" action="<?=$this->url('usuario',['action'=>'remover','id'=>$id])?>">
    <div class="form-group">
        <input type="hidden" name="id" value="<?=$id?>">
        <input type="submit" class="btn btn-danger"  name="del" value="Não">
        <input type="submit" class="btn btn-success " name="del" value="Sim">
       
    </div>
</form> 